App/models.py
  
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from App import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)

    # exam resualt

   

    def get_reset_token(self, expires_sec=1800):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"


class  subject(db.Model):
    __tablename__ = 'subject'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), unique=True, nullable=False)
    def __repr__(self):
        return f"subject('{self.name}')"

# Questions Model

class Questions(db.Model):
    __tablename__ = 'questions'
    qid = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(100), nullable=False)
    question = db.Column(db.String(100), nullable=False)
    option1 = db.Column(db.String(100), nullable=False)
    option2 = db.Column(db.String(100), nullable=False)
    option3 = db.Column(db.String(100), nullable=False)
    option4 = db.Column(db.String(100), nullable=False)
    
    answer = db.Column(db.String(100), nullable=False)
 

    def __repr__(self):
        return f"Questions('{self.question}', '{self.answer}')"

App/questions/forms.py
from secrets import choice
from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField, TextAreaField,SelectField
from wtforms.validators import DataRequired
from App.models import subject







class AddQuestionForm(FlaskForm):
    
    subject = SelectField('Subject', validators=[DataRequired()],choices=[])
    question = TextAreaField('Question', validators=[DataRequired()])
    option1 = StringField('Option 1', validators=[DataRequired()])
    option2 = StringField('Option 2', validators=[DataRequired()])
    option3 = StringField('Option 3', validators=[DataRequired()])
    option4 = StringField('Option 4', validators=[DataRequired()])
    answer = StringField('Answer', validators=[DataRequired()])
    submit = SubmitField('Add Question')

    def __init__(self, *args, **kwargs):
        super(AddQuestionForm, self).__init__(*args, **kwargs)
        self.subject.choices = [(subject.id, subject.name) for subject in subject.query.all()]

# update Question form

class UpdateQuestionForm(FlaskForm):
    subject = StringField('Subject', validators=[DataRequired()])
    question = TextAreaField('Question', validators=[DataRequired()])
    option1 = StringField('Option 1', validators=[DataRequired()])
    option2 = StringField('Option 2', validators=[DataRequired()])
    option3 = StringField('Option 3', validators=[DataRequired()])
    option4 = StringField('Option 4', validators=[DataRequired()])
    answer = StringField('Answer', validators=[DataRequired()])
    submit = SubmitField('Update Question')

App/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_mail import Mail
from App.config import Config


db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from App.auth.views import users
    from App.questions.views import questions
    from App.main.views import main
    app.register_blueprint(users)
    app.register_blueprint(questions)
    app.register_blueprint(main)


    # with app.app_context():
    #     db.create_all()


    

    return app

App/main/views.py
from flask import render_template, request, Blueprint



main = Blueprint('main', __name__)


@main.route("/")

def home():

    return render_template('home.html', title='Home')


@main.route("/about")
def about():
    return render_template('about.html', title='About')

App/questions/views.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from App import db

from App.models import Questions
from App.questions.forms import AddQuestionForm, UpdateQuestionForm


questions = Blueprint('questions', __name__)


@questions.route("/add_question", methods=['GET', 'POST'])
# @login_required
def add_question():
    form = AddQuestionForm()
    if form.validate_on_submit():
        question = Questions(subject=form.subject.data,
                             question=form.question.data,
                             option1=form.option1.data,
                             option2=form.option2.data,
                             option3=form.option3.data,
                             option4=form.option4.data,
                             answer=form.answer.data)
        db.session.add(question)
        db.session.commit()
        flash('Question added successfully', 'success')
        return redirect(url_for('main.home'))
    return render_template('Admin/add_question.html', title='Add Question', form=form, legend='Add Question')


@questions.route("/question/<int:qid>")
def question(qid):
    question = Questions.query.get_or_404(qid)
    return render_template('question.html', title=question.question, question=question)

# update question
@questions.route("/question/<int:qid>/update", methods=['GET', 'POST'])
@login_required
def update_question(qid):
 
    form = UpdateQuestionForm()
    if form.validate_on_submit():
        question.subject = form.subject.data
        question.question = form.question.data
        question.option1 = form.option1.data
        question.option2 = form.option2.data
        question.option3 = form.option3.data
        question.option4 = form.option4.data
        question.answer = form.answer.data
        db.session.commit()
        flash('Question updated successfully', 'success')
        return redirect(url_for('questions.question', qid=question.id))
    elif request.method == 'GET':
        form.subject.data = question.subject
        form.question.data = question.question
        form.option1.data = question.option1
        form.option2.data = question.option2
        form.option3.data = question.option3
        form.option4.data = question.option4
        form.answer.data = question.answer
    return render_template('add_question.html', title='Update Question', form=form, legend='Update Question')

# all questions
@questions.route("/questions")
# @login_required
@login_required
def all_questions():
    page = request.args.get('page', 1, type=int)
    questions = Questions.query.order_by(Questions.qid.asc()).paginate(page=page, per_page=1)
    return render_template('exam.html', questions=questions)

# # delete question
# @questions.route("/question/<int:qid>/delete", methods=['POST'])
# 
# def delete_question(qid):
#     question = Questions.query.get_or_404(qid)
#     db.session.delete(question)
#     db.session.commit()
#     flash('Question deleted successfully', 'success')
#     return redirect(url_for('questions.questions'))





         

App/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

App/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
       <div class="container">
           <div class="row">
               <div class="col-md-8">
                   <div class="card">
                       <div class="card-body">
                        <form method="POST" action="" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Account Info</legend>
                                <div class="form-group">
                                    {{ form.username.label(class="form-control-label") }}
                
                                    {% if form.username.errors %}
                                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.username.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.username(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.email.label(class="form-control-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.picture.label() }} <br>
                                    {{ form.picture(class="form-control-file") }}
                                    {% if form.picture.errors %}
                                        {% for error in form.picture.errors %}
                                            <span class="text-danger">{{ error }}</span></br>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </fieldset>
                            <div class="form-group">
                                {{ form.submit(class="btn btn-outline-info mt-2") }}
                            </div>
                        </form>
                       </div>
                   </div>
               </div>
           </div>
       </div>
    </div>
{% endblock content %}

App/templates/exam.html
{% extends "layout.html" %}
{% block content %}

<style>
  .video{
    background-color: aqua;
    height: 300px;
  }
  .quiz-card{
    background-color: #f5f5f5;
    padding: 10px;
    margin: 10px;
    border: 1px solid #ccf;
  }
  .block{
    /* display inline block */
   
    flex-direction: end;
    float: right;


  }
  .next{
    background-color: #f5f5f5;
    padding: 10px;
    margin: 10px;
    float: right;
    border: 1px solid #ccc;
  }
</style>

    <div class="container">
      <div class="row">

        <div class="col-md-5">

          <!-- exams qustion  -->
          <!-- exam Rules -->

          <div class="card">
            <div class="card-body">
              <h1>Video Will be Here</h1>
              
              <div class="video">

              </div>
            </div>
          <!-- button -->
          
         
            </div>
         
        </div>
        <div class="col-md-7">
          <div class="card">
            <div class="card-body">
              <!-- loop question and aswer -->
              <h1>Question Will be Here</h1>
              {% for q in questions.items %}

              <div class="card quiz-card">
                <div class="card-body">
                  <h5 class="card-title">{{q.qid}} .{{q.question}}</h5>
                 
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                    <label class="form-check-label" for="exampleRadios1">
                      {{q.option1}}
                      
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                    <label class="form-check-label" for="exampleRadios1">
                      {{q.option2}}
                      
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                    <label class="form-check-label" for="exampleRadios1">
                      {{q.option3}}
                      
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                    <label class="form-check-label" for="exampleRadios1">
                      {{q.option4}}
                      
                    </label>
                  </div>

                </div>
              </div>


                
              
              {% endfor %}




              
        
            </div>
          <!-- button -->


              <div class="next">
                {% for page_num in questions.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
{% if page_num %}
  {% if questions.page == page_num %}
    <a class="btn  col-md-2 btn-info mb-4 " href="{{url_for('questions.all_questions',page=page_num)}}">{{page_num}}</a>
    
  {% else %}
    <a class="btn btn-outline-info col-md-2 block" href="{{url_for('questions.all_questions',page=page_num)}}">{{page_num}}</a>
  {% endif %}
{% else %}
  ...
{% endif %}
{% endfor %}

              </div>
          
         
            </div>
        </div>
     
        </div>
      </div>
    </div>

{% endblock content %}

App/templates/home.html
{% extends "layout.html" %}
{% block content %}

    <div class="container">
      <div class="row">

        <div class="col-md-7">

          <!-- exams qustion  -->
          <!-- exam Rules -->

          <div class="card">
            <div class="card-body">
              <h1>Exam Rules</h1>
              <ul>
                <li>1. The exam consists of 10 questions.</li>
                <li>2. Each question carries 10 marks.</li>
                <li>3. There is no negative marking.</li>
                <li>4. You have 10 minutes to complete the exam.</li>
                <li>5. You can't go back to previous question.</li>
                <li>6. You can't change your answer once you have selected it.</li>
                <li>7. You can't pause the exam.</li>
                <li>8. You can't leave the exam once you have started it.</li>
              </ul>
              <a class="btn btn btn-warning" href="{{url_for('questions.all_questions')}}">Start Exam</a>
            </div>
          <!-- button -->
          
         
            </div>
         
        </div>
        <div class="col-md-5">
          <img src="{{url_for('static',filename='assets/motive.png')}}" alt="" height="300">
        </div>
     
        </div>
      </div>
    </div>

{% endblock content %}

App/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css"
rel="stylesheet"
/>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Exams - {{ title }}</title>
    {% else %}
        <title>Exams</title>
    {% endif %}
</head>
<body>
    <!-- Navbar -->
    <header class="site-header">
<nav class="navbar navbar-expand-lg navbar-light bg-#f4f1de fixed-top">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        Exams App
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        </li>
      
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
    

      {% if current_user.is_authenticated %}

      <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
      <!-- Avatar -->
      <div class="dropdown">
        <a
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuAvatar"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}"
            class="rounded-circle"
            height="25"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuAvatar"
        >
          <li>
            <a class="dropdown-item" href="{{ url_for('users.account') }}">My profile</a>
          </li>
         
          <li>
            <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
    {% else %}

    <a class="text-reset me-3" href="{{ url_for('users.login') }}">
     Login
    </a>

    <a class="text-reset me-3" href="{{ url_for('users.register') }}">
      Register
     </a>

    {% endif %}


    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
    </header>
<!-- Navbar -->
    <main role="main" class="container mt-4">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
         
        </div>
       
      </div>
      {% block content %}{% endblock %}

    </main>


    <!-- footer -->

    <footer class="footer text-center text-lg-start  fixed-bottom">
      <!-- Grid container -->

    

      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center p-3" >
        © 2022 Copyright:
        <a class="text-dark" href="#">Exams</a>
      </div>
      <!-- Copyright -->
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <!-- MDB -->

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"
    ></script>
</body>
</html>

App/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="">
        <div class="container">
         <div class="row">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Welcome Back 👋</legend>
                                <div class="form-group">
                                    {{ form.email.label(class="form-control-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.password.label(class="form-control-label") }}
                                    {% if form.password.errors %}
                                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.password.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-check mt-2">
                                    {{ form.remember(class="form-check-input") }}
                                    {{ form.remember.label(class="form-check-label") }}
                                </div>
                            </fieldset>
                            <div class="form-group">
                                {{ form.submit(class="btn btn-success") }} <br>

                                <small class="text-muted mt-2">
                                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                                </small>
                            </div>
                        </form>

                        <div class="border-top pt-3">
                            <small class="text-muted ml-2">
                                Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
                            </small>
                        </div>
                    </div>

                    

                    <p class="mt-4"></p>
                
                </div>
            </div>
            <div class="col-md-5">
                <img src="{{url_for('static',filename='assets/login.png')}}" alt="" height="300">
            </div>
         </div>
        </div>
    </div>
  
{% endblock content %}

App/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Join Us Today 👉</legend>
                                <div class="form-group">
                                    {{ form.username.label(class="form-control-label") }}
                
                                    {% if form.username.errors %}
                                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.username.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.username(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.email.label(class="form-control-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.password.label(class="form-control-label") }}
                                    {% if form.password.errors %}
                                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.password.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.confirm_password.label(class="form-control-label") }}
                                    {% if form.confirm_password.errors %}
                                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.confirm_password.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.confirm_password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                            </fieldset>
                            <div class="form-group mt-2">
                                {{ form.submit(class="btn btn-success") }}
                            </div>
                        </form>

                        <div class="border-top pt-3">
                            <small class="text-muted">
                                Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <img src="{{url_for('static',filename='assets/signup.png')}}" alt="" height="290">
            </div>
        </div>
       
    </div>
  
{% endblock content %}

App/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3"> by {{ user.username }} </h1>
    
   
{% endblock content %}